# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17nbwhotbC5Vc5wnUKV4DlEBMm39wLC6u

##Name    : B.Renuka
##class   : 4th year
##Roll NO : 21X05A6709
##Branch  : Data Science
##College : Narsimha Reddy Engineering College
"""



"""#Project Title :
###To predict the Heart attach disease for organisation WHO(World Health Organisation),using Machine Learning algorithm rate of heart attack disease will increasing manner or decreasing manner
"""